workflows:
  my-workflow:
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: master
          include: false
      cancel_previous_builds: true
    scripts:
      - name: Build Android APK
        working_directory: android
        script: ./gradlew assembleRelease
    artifacts:
      - app\outputs\apk\release\app-release.apk
